### ISSUE TITLE
Token vs Token Secret

### ISSUE THREAD

**Issue by Sumitforyou** [broidHQ/integrations#147]
# Overview
- What project is this issue for?: 
broid-messenger

Can anyone Please explain difference between token and token secret ?
How to obtain those and please do provide sample values for both?

**Comment by killix** [comment]
Hi @Sumitforyou,

Sorry for the late response.

`token` should be the token that Facebook give you when you configure your app.
`tokenSecret` is the `verify_token` (hub.verify_token) you configure when you activate the webhook on you facebook app.

Let me know if you need more details.

**Comment by killix** [comment]
i added details in the readme of the integration: https://github.com/broidHQ/integrations/commit/81d39869d4e287036692f9febdd9f0aa42fe64e5

**Comment by Sumitforyou** [comment]
Thank you for the explaination...
