### ISSUE TITLE
Move to yarn?

### ISSUE THREAD

**Issue by lesyk** [broidHQ/integrations#174]
# Overview
- What project is this issue for?: all
- Is this a bug, security, feature request, or feedback: feature

## Details
Move from npm to yarn? Want to know what people think about such change? Are there any reasons not to?

**Comment by killix** [comment]
We already use `yarn`. Do you have something other in your mind? ;)

**Comment by lesyk** [comment]
In documentations we have: `npm install --save @broid/slack` we need to change that to `yarn add @broid/slack`

**Comment by dustinblackman** [comment]
I'd rather `npm` be the default when it comes to documentation as not everyone has made their way over to `yarn`. We can possibly have both however as I've seen done quite often.
