### ISSUE TITLE
Conversations, dialogs, router, actions, etc.

### ISSUE THREAD

**Issue by lesyk** [broidHQ/integrations#176]
# Overview
- Is this a bug, security, feature request, or feedback: **question**

## Details
I used Botframework from Microsoft for a while, there they have concepts like conversations, dialogs, router, actions, etc., are there any plans to implement them here? If not, what would you suggest to use for having such abstractions?

Currently I am struggling to make architecture, where bot can have more than one message conversation. How usually it is done with this framework? Back in botframework, they use waterfall model of conversation, what is the paradigm here?

**Comment by killix** [comment]
I need to check in details how it really works with botframework. But as you can see we use a [conversation id](https://github.com/broidHQ/integrations/blob/master/broid-skype/src/core/Parser.ts#L67) in a context object to make the possibility of the bot/app to route the answer correctly.

About dialogs, router, actions it's something we support in others integrations, we need to add it in the MS integrations (Skype and MS Teams).

**Comment by lesyk** [comment]
Here are really important (to me) concepts:
## Waterflow

In botframeworks to crate dialog I would do some thing like this:
```
bot.dialog('greetings', [
    // Step 1
    function (session) {
        builder.Prompts.text(session, 'Hi! What is your name?');
    },
    // Step 2
    function (session, results) {
        session.endDialog('Hello %s!', results.response);
    }
]);
```
Thus, as soon as I am in greetings dialog, bot asks about name, use reply, and then it prints it.

## Dialog
```
bot.dialog('greetings', [
    function (session) {
        session.beginDialog('askName');
    },
    function (session, results) {
        session.endDialog('Hello %s!', results.response);
    }
]);
bot.dialog('askName', [
    function (session) {
        builder.Prompts.text(session, 'Hi! What is your name?');
    },
    function (session, results) {
        if(results.response){         
          session.endDialogWithResult({
            response: null,
            resumed: builder.ResumeReason.back
          });
        }
   }
]);
```
In this example, chats begins from greetings dialog; where bot starts dialog askName, thus, user gets question 'Hi! What is your name?', when user replies, answer is pushed back to greetings dialog and message 'Hello...' shown.

##
Maybe I am asking wrong questions, but with current setup it is unclear for me how to implement those concepts.
The only solution which I see now is to save in nodejs's memory all users and stages of their conversations. So, as soon as new text is sent I do look up by user id fetch dialog id (place where message was sent last time) and direct that communication to that place.
You thoughts?
