### ISSUE TITLE
Re-license AGPL to MIT/Apache

### ISSUE THREAD

**Issue by bobsaggirty** [broidHQ/integrations#206]
# Overview
- What project is this issue for?: `integrations`

- Is this a bug, security, feature request, or feedback: Feedback

## Details
First, thanks for the work put into building and open sourcing this library!

The AGPL license on this project is pretty restrictive, especially when used in the context of Node applications where code is not truly "linked". There is some controversy over how the AGPL would actually be executed for these cases, but Google has out right banned the use of AGPL software in their organization due to liability issues: [https://opensource.google.com/docs/thirdparty/licenses/#agpl-affero-gpl-not-allowed](https://opensource.google.com/docs/thirdparty/licenses/#agpl-affero-gpl-not-allowed) of having to release any proprietary source code that might touch the AGPL code. Because of Google's stance on this, many developers and companies refuse to use / contribute to AGPL projects.

Would you consider re-licensing the project to a more permissive MIT or Apache 2.0 license. It seems like some of the other projects like [`broid-kit`](https://github.com/broidHQ/broid-kit) are already using an Apache 2.0 license, however, the fact that they rely on `integrations` is an issue.

## Feature Overview
Choosing a more permissive license.

## Steps to Reproduce
[LICENSE.md](https://github.com/broidHQ/integrations/blob/master/LICENCE.md)

## Observed
AGPL

## Expected
MIT or Apache 2.0

**Comment by killix** [comment]
Thanks for your comment. I will close the issue since is not something we will do now.

> Would you consider re-licensing the project to a more permissive MIT or Apache 2.0 license. It seems like some of the other projects like broid-kit are already using an Apache 2.0 license, however, the fact that they rely on integrations is an issue.

Regarding to the licence using "broid-kit" is not an issue with the licence of the integrations.
Backdoor licence is not exist (https://www.mongodb.com/blog/post/the-agpl)
