### ISSUE TITLE
Integration with Botkit

### ISSUE THREAD

**Issue by znat** [broidHQ/integrations#69]
Hi Guys,
Just wondering if you had any recommendation regarding how to integrate Broid with Botkit?

**Comment by killix** [comment]
Hi,

Can you give more details about what you want to do exactly?
You have many possibilities, all depends of what you want to use in botkit side.

**Comment by znat** [comment]
For incoming messages, Broid would convert messages coming from say FB or
Slack. I understand that Broid provides an observable from which incoming
messages are received. How would you recommend to interface this observable
with Botkit's `hears` callback that listens to a pattern in the user
utterance?
Is there a conversion API (a function) that can be called from a Botkit's
middleware?
Thanks

Le jeu. 23 févr. 2017 9:53 AM, Issam Hakimi <notifications@github.com> a
écrit :

**Comment by killix** [comment]
i will take a look on that this week to see how we can do that properly.

**Comment by killix** [comment]
We still to figure out how we can do that. May be one good solution is create a `BroidKit` to include all features provide by `botkit`. I don't know.

**Comment by znat** [comment]
I like the name :) 
What about a Broid middleware to Botkit ?

**Comment by killix** [comment]
It's something we can support later. Off course. Let me this week to think about this idea.

**Comment by killix** [comment]
can be fix now with https://github.com/broidHQ/broid-kit
