### ISSUE TITLE
Integrate with existing Express application

### ISSUE THREAD

**Issue by jcampbell05** [broidHQ/integrations#71]
I've been looking into how to implement this into Bottr from the issue you left their, for technical reasons to due to some of the features we wish to roll out we need to control where the endpoints get mounted.

Currently we do this by using the ability to embed an express route inside of another express route.

We wouldn't be able to support the way broidHQ kickstarts express listening, so we would need this to be fixed in order to be able to support broid.

**Comment by killix** [comment]
We working on something like that. Let us some time before publish our work.

**Comment by jcampbell05** [comment]
@killix Awesome :) let me know if I can help :)

**Comment by killix** [comment]
We actually testing all the integrations to be sure, we not introduced regression somewhere. We will able to merge after that.

**Comment by killix** [comment]
Fixed with the version 2.2.0. @jcampbell05 take a look to https://github.com/broidHQ/broid-kit ;)
