### ISSUE TITLE
Error 400 with broid-messenger due to nonexisting field "name" for user

### ISSUE THREAD

**Issue by acailly** [broidHQ/integrations#73]
# Overview
- What project is this issue for?: broid-messenger
- Is this a bug, security, feature request, or feedback: bug

## Steps to Reproduce

Talk to my bot

## Observed

```
Something went wrong: 400 - {"error":{"message":"(#100) Tried accessing nonexisting field (name) on node type (MessengerPageScopedID)","type":"OAuthException","code":100,"fbtrace_id":"EH1sMyJphfS"}}
```

broid-messenger tries to get some fields relative to connected user. These are name, first_name, last_name (see adapter.js line 202).

I checked the properties available from my account with the following request:

```
GET https://graph.facebook.com/v2.8/<myid>?&access_token=<mytoken>
```

and I get:

```
{
   "first_name": <value>,
   "last_name": <value>,
   "profile_pic": <value>,
   "locale": <value>,
   "timezone": <value>,
   "gender": <value>
}
```

No sign of `name` field.

## Expected

Is the `name` field really needed.
I tried to run a bot with botpress.io and it worked well so the problem is not with my account.
Maybe `first_name` and `last_name` is sufficient ?

**Comment by killix** [comment]
i can't repro the bug. But it's a good idea to replace name by `first_name` and `last_name`.
