### ISSUE TITLE
broid-alexa cannot be resolved

### ISSUE THREAD

**Issue by jcampbell05** [broidHQ/integrations#82]
`broid-alexa` cannot be resolved, when using NPM version 3. However it does exist in my modules, not sure if there is anything I can do ?

**Comment by killix** [comment]
Can you send me the exact command you try?
All look good for me:

![screen shot 2017-03-13 at 8 54 11 am](https://cloud.githubusercontent.com/assets/1795343/23855080/b17cd654-07ca-11e7-84f8-d18f142d4149.png)

**Comment by james-aiwip** [comment]
So I install like so `npm install --save broid-alexa` and it installed correctly however `var broidAlexa = require('broid-alexa')` fails to locate it under NPM 3

**Comment by killix** [comment]
ok found it the issue is coming from https://github.com/broidHQ/integrations/blob/master/broid-alexa/package.json#L4
 i will fix it.

**Comment by killix** [comment]
fix with version 1.0.1
